name: CI/CD Process
on:
  workflow_call:
  workflow_dispatch:

jobs:
  success:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.3.0
      - name: Configure git
        run: |
          git config --global user.name "Danilo Pianini"
          git config --global user.email "danilo.pianini@unibo.it"
      - name: fetch the java version
        id: java-version
        run: echo "java-version=$(grep 'FROM eclipse-temurin' < Dockerfile | sed 's/FROM eclipse-temurin://')" >> $GITHUB_OUTPUT
      - uses: actions/setup-java@v4.7.1
        with:
          distribution: 'temurin'
          java-version: ${{ steps.java-version.outputs.java-version }}
      - name: Run on existing projects
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOMERGE_TOKEN }}
        run: |
          ./process.main.kts unibo-oop-projects/OOP23-LucaFerar-Soprnzetti-Vdamianob-Velli-wulf
          ./process.main.kts unibo-oop-projects/OOP23-ChristianRemschiC-GiorgiaPateraGior-ClaudiuRemschi-GiorgiaPatera-JagoCamoni-Unknown-GrubClash
          ./process.main.kts unibo-oop-projects/OOP24-Claudio-ClaudioLodi-LodiClaudio-LuigiLinari-Tbandini-TommasoBandini-TommasoGoni-Emberline
