name: CI/CD Process
on:
  workflow_call:
  workflow_dispatch:

jobs:
  success:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
      - name: Configure git
        run: |
          git config --global user.name "Danilo Pianini"
          git config --global user.email "danilo.pianini@unibo.it"
      - name: fetch the java version
        id: java-version
        run: echo "java-version=$(grep 'FROM eclipse-temurin' < Dockerfile | sed 's/FROM eclipse-temurin://')" >> $GITHUB_OUTPUT
      - uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: ${{ steps.java-version.outputs.java-version }}
      - name: Run on existing repository
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOMERGE_TOKEN }}
        run: ./process.main.kts unibo-oop-projects/OOP23-LucaFerar-Soprnzetti-Vdamianob-Velli-wulf
